name: Sync branches with dev

on:
  push:
    branches:
      - dev

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Sync staging with dev
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff dev -m "Auto-merge dev into staging"
          git push
      - name: Sync polygon with dev
        run: |
          git checkout polygon
          git pull
          git merge --no-ff dev -m "Auto-merge dev into polygon"
          git push
      - name: Sync arbitrum with dev
        run: |
          git checkout arbitrum
          git pull
          git merge --no-ff dev -m "Auto-merge dev into arbitrum"
          git push
      - name: Sync optimism with dev
        run: |
          git checkout optimism
          git pull
          git merge --no-ff dev -m "Auto-merge dev into optimism"
          git push
